###
POST http://api.hotel.com/v1/auth/login
Content-Type: application/json

{
    "usernameOrEmail": "kwamegilbert1114@gmail.com", 
    "password": "1234"
}
###

GET http://api.hotel.com/v1/auth

###
// SEND OTP
POST http://api.hotel.com/v1/auth/forgot-password
Content-Type: application/json

{
    "email": "kwamegilbert1114@gmail.com"
}

// Get room availability
GET http://api.hotel.com/v1/rooms/availability/branch/


        

        
    
    
    
    
        
        
        
    


